scrollback_lines 10000

font_family FiraCode Nerd Font
font_size 11.0
disable_ligatures never


foreground #c5c8c6
background #1d1f21
background_opacity 0.8

kitty_mod ctrl+shift
copy_on_select yes
rectangle_select_modifiers ctrl+alt

tab_activity_symbol *
tab_title_template "{index}:{title.split('shervin@fractal:')[-1]}"

include dracula.conf
