#!/bin/bash

dir="$HOME/.config/polybar"
style="$1"

launch_bar() {
	# kill existing bars and wait until the processes have been shut down
	pkill -x polybar
	while pgrep -u $UID -x polybar >/dev/null; do 
		sleep 1
	done

	# launch the bar
	polybar -q top -c "$dir/$style/config" &
	polybar -q bottom -c "$dir/$style/config" &	
}

case "$style" in
	mine)
		launch_bar 
	;;

	help|*)
		cat <<- EOF
		Usage: launch.sh <theme>
		Available Themes: mine
		EOF
	;;
esac
