#!/bin/bash

wallpaper="$HOME/.local/share/wallpapers/moon-3440x1440.jpg"

MENU="$(rofi -font 'Fire Code Retina 15' -theme solarized_alternate -sep "|" \
	-dmenu -i -p 'System' -location 3 -xoffset -10 -yoffset 32 -width 10 \
	-hide-scrollbar -line-padding 4 -padding 20 -lines 4 \
	<<< " Lock| Logout| Reboot| Shutdown")"
            case "$MENU" in
                *Lock) betterlockscreen --update $wallpaper --lock dim;;
                *Logout) openbox --exit || i3-msg exit;;
                *Reboot) systemctl reboot ;;
                *Shutdown) systemctl -i poweroff
            esac
